spring:
  ### h2 설정 ###
  #  h2:
  #    console:
  #      enabled: true
  #  datasource:
  #    url: jdbc:h2:~/test
  #    username: sa
  #    password:
  #    driver-class-name: org.h2.Driver
  ### mysql 드라이버 설정 ###
  datasource:
    url: jdbc:mysql://localhost:3306/shopping-sehyeon
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  ### jpa 설정 ###
  jpa:
    hibernate:
      # create = 테이블을 만들기만
      # update = 테이블 없으면 만들고, entity랑 다르면 수정 -> 삭제는 안해줌
      # validate = 테이블이랑 entity랑 맞는지 확인만
      # none = 아무것도 안함
      # create-drop = create랑 똑같은데, 애플리케이션 종료시점에 테이블 drop => 테스트코드에서만 쓰세요
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true # SQL문을 보기 좋게 출력
        #        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        jdbc:
          time_zone: Asia/Seoul
    show-sql: true

jwt:
  secret: ${kt.jwt.secret:kt-cloud-shopping-kt-cloud-shopping-kt-cloud-shopping-kt-cloud-shopping}
  access-token-expiration: ${kt.jwt.access-token-expiration:3000000} #5분
  refresh-token-expiration: ${kt.jwt.refresh-token-expiration:43200000} #12시간

slack:
  bot-token: ${slack.token}
  log-channel: ${slack.channel}

common:
  common-value: this is common value
  common-value-param: this is common value with param - ${COMMON_PARAM:공통}

test:
  my-value: this is test value in local
  my-value-param: this is test value with param - ${TEST_PARAM:terry}