name: pr-test
on: pull_request

env:
  DB_PASSWORD: root

jobs:
  pr-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Start Redis Service
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 6

      - name: Start MySQL Service
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE shopping;' -uroot -proot

      - name: Set up JDK 21
        uses: actions/setup-java@main
        with:
          java-version: '21'
          cache: 'gradle'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.5

      - name: Run Test
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: wrapper
          arguments: test



